### ISSUE TITLE
New Static Site Generator?

### ISSUE THREAD

**Issue by Sean-BREI** [BarkleyREI/generator-brei-gulp#3]
The [gulp-assemble](https://github.com/assemble/gulp-assemble) project has been deprecated. However, Assemble can still be used directly with or without Gulp. Though, it might be in our best interest to seek out and research other competing Static Site Generators to avoid conflict in the future with said Task Runner.

[StaticGen](https://www.staticgen.com/) would be a good resource for researching Open-Source Static Site Generators as well as their corresponding templating languages.

Optional: An entirely new templating language or language that can be used in conjunction with Handlebars.js. E.g. [Liquid](https://github.com/Shopify/liquid)

**Comment by nessthehero** [comment]
This issue was moved to BarkleyREI/generator-brei-app#207
